const STATIC_DATE = new Date('2025-01-01T00:00:00.000Z');

export const TEACHERS = [
  {
    id: 9999,
    name: 'Admin User',
    code: 'SU',
    email: 'admin@almaarif.id',
    password: 'admin',
    role: 'admin' as const,
  },
  {
    id: 1,
    code: 'A',
    name: "K. Syamsul Ma'arif",
    email: 'syamsul.maarif@almaarif.id',
    password: 'syamsul123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=11',
    birthPlace: 'Jambi',
    birthDate: '1982-03-15',
    address: 'Jl. KH. Ahmad Dahlan No. 12, Jambi',
    phone: '081234567001',
    formalEducation: 'S.Ag',
    boardingEducation: 'Pesantren Daar el-Qolam',
    position: 'Kepala Sekolah',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 2,
    code: 'B',
    name: 'Ust. Istamar',
    email: 'istamar@almaarif.id',
    password: 'istamar123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=12',
    birthPlace: 'Palembang',
    birthDate: '1985-07-22',
    address: 'Jl. Merdeka No. 45, Palembang',
    phone: '081234567002',
    formalEducation: 'S.Pd.I',
    boardingEducation: 'Pesantren Al-Mukmin',
    position: 'Waka Kurikulum',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 3,
    code: 'C',
    name: 'Achmad Qosyidin',
    email: 'achmad.qosyidin@almaarif.id',
    password: 'achmad123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=13',
    birthPlace: 'Banjarmasin',
    birthDate: '1988-11-10',
    address: 'Jl. Pangeran Antasari No. 8, Banjarmasin',
    phone: '081234567003',
    formalEducation: 'S.Pd',
    boardingEducation: "Pesantren Darullughah Wadda'wah",
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 4,
    code: 'D',
    name: 'Nurul Iman Saputra',
    email: 'nurul.iman@almaarif.id',
    password: 'nurul123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=14',
    birthPlace: 'Jakarta',
    birthDate: '1990-02-28',
    address: 'Jl. Kramat Raya No. 21, Jakarta Pusat',
    phone: '081234567004',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Tebuireng',
    position: 'Guru Tahfidz',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 5,
    code: 'E',
    name: 'Ilham Aditia Nurohman',
    email: 'ilham.aditia@almaarif.id',
    password: 'ilham123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=15',
    birthPlace: 'Bandung',
    birthDate: '1991-06-05',
    address: 'Jl. Dago No. 33, Bandung',
    phone: '081234567005',
    formalEducation: 'S.Kom',
    boardingEducation: 'Pesantren Cipasung',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 6,
    code: 'F',
    name: 'Irfan Ramadhan',
    email: 'irfan.ramadhan@almaarif.id',
    password: 'irfan123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=16',
    birthPlace: 'Surabaya',
    birthDate: '1987-09-18',
    address: 'Jl. Pemuda No. 17, Surabaya',
    phone: '081234567006',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Lirboyo',
    position: 'Guru Tahfidz',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 7,
    code: 'G',
    name: "Imron Ma'arif",
    email: 'imron.maarif@almaarif.id',
    password: 'imron123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=17',
    birthPlace: 'Yogyakarta',
    birthDate: '1983-12-01',
    address: 'Jl. Malioboro No. 5, Yogyakarta',
    phone: '081234567007',
    formalEducation: 'S.Ag',
    boardingEducation: 'Pesantren Krapyak',
    position: 'Waka Kesiswaan',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 8,
    code: 'H',
    name: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@almaarif.id',
    password: 'ahmad123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=18',
    birthPlace: 'Malang',
    birthDate: '1989-04-12',
    address: 'Jl. Sultan Agung No. 29, Malang',
    phone: '081234567008',
    formalEducation: 'S.Pd.I',
    boardingEducation: 'Pesantren Gontor',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 9,
    code: 'I',
    name: "Ary Sya'bana",
    email: 'ary.syabana@almaarif.id',
    password: 'ary123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=19',
    birthPlace: 'Medan',
    birthDate: '1992-08-25',
    address: 'Jl. Pandeglang No. 11, Medan',
    phone: '081234567009',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Musthafawiyah',
    position: 'Guru Tahfidz',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 10,
    code: 'J',
    name: 'Ridho Pratama',
    email: 'ridho.pratama@almaarif.id',
    password: 'ridho123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=20',
    birthPlace: 'Pekanbaru',
    birthDate: '1993-01-30',
    address: 'Jl. Sudirman No. 8, Pekanbaru',
    phone: '081234567010',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Hidayatullah',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 11,
    code: 'K',
    name: 'Asykur',
    email: 'asykur@almaarif.id',
    password: 'asykur123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=21',
    birthPlace: 'Lombok',
    birthDate: '1986-05-14',
    address: 'Jl. Raya Mataram No. 7, Lombok',
    phone: '081234567011',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Nurul Hakim',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 12,
    code: 'L',
    name: 'Umi Dewi Anjariyah',
    email: 'umi.dewi@almaarif.id',
    password: 'umi123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=22',
    birthPlace: 'Semarang',
    birthDate: '1984-10-08',
    address: 'Jl. Pandanaran No. 15, Semarang',
    phone: '081234567012',
    formalEducation: 'S.Pd.I',
    boardingEducation: 'Pesantren Al-Munawwir',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 13,
    code: 'M',
    name: 'Indah Nur Fadhilah',
    email: 'indah.nur@almaarif.id',
    password: 'indah123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=23',
    birthPlace: 'Bogor',
    birthDate: '1993-12-20',
    address: 'Jl. Pajajaran No. 3, Bogor',
    phone: '081234567013',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Daarul Quran',
    position: 'Guru Tahfidz',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 14,
    code: 'N',
    name: "Ni'matul Laely",
    email: 'nimatul.laely@almaarif.id',
    password: 'nimatul123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=24',
    birthPlace: 'Sidoarjo',
    birthDate: '1990-07-16',
    address: 'Jl. Raya Sidoarjo No. 25, Sidoarjo',
    phone: '081234567014',
    formalEducation: 'S.Pd.I',
    boardingEducation: 'Pesantren Sidogiri',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 15,
    code: 'O',
    name: 'Tri Lestari',
    email: 'tri.lestari@almaarif.id',
    password: 'tri123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=25',
    birthPlace: 'Solo',
    birthDate: '1988-03-25',
    address: 'Jl. Slamet Riyadi No. 42, Solo',
    phone: '081234567015',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Al-Muayyad',
    position: 'Waka Kurikulum',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 16,
    code: 'P',
    name: 'Istiqomah M.',
    email: 'istiqomah@almaarif.id',
    password: 'istiqomah123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=26',
    birthPlace: 'Tangerang',
    birthDate: '1991-11-09',
    address: 'Jl. BSD Raya No. 18, Tangerang',
    phone: '081234567016',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Al-Amanah',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 17,
    code: 'Q',
    name: 'Putri Ulfa Sari',
    email: 'putri.ulfa@almaarif.id',
    password: 'putri123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=27',
    birthPlace: 'Padang',
    birthDate: '1987-09-30',
    address: 'Jl. Khatib Sulaiman No. 10, Padang',
    phone: '081234567017',
    formalEducation: 'S.Pd.I',
    boardingEducation: 'Pesantren Sumatera Thawalib',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 18,
    code: 'R',
    name: 'Nur Hasanah',
    email: 'nur.hasanah@almaarif.id',
    password: 'nur123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=28',
    birthPlace: 'Cirebon',
    birthDate: '1985-02-14',
    address: 'Jl. Karanggetas No. 6, Cirebon',
    phone: '081234567018',
    formalEducation: 'S.Ag',
    boardingEducation: 'Pesantren Buntet',
    position: 'Guru Tahfidz',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 19,
    code: 'S',
    name: "Robi'ah Adawiah",
    email: 'robiah.adawiah@almaarif.id',
    password: 'robiah123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=29',
    birthPlace: 'Banyuwangi',
    birthDate: '1989-06-22',
    address: 'Jl. Diponegoro No. 31, Banyuwangi',
    phone: '081234567019',
    formalEducation: 'S.Pd',
    boardingEducation: 'Pesantren Al-Qodiri',
    position: 'Guru',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
  {
    id: 20,
    code: 'T',
    name: 'Irfatul Ulum',
    email: 'irfatul.ulum@almaarif.id',
    password: 'irfatul123',
    role: 'teacher' as const,
    photo: 'https://i.pravatar.cc/300?img=30',
    birthPlace: 'Kediri',
    birthDate: '1986-08-19',
    address: 'Jl. Dhoho No. 14, Kediri',
    phone: '081234567020',
    formalEducation: 'S.Pd.I',
    boardingEducation: 'Pesantren Lirboyo',
    position: 'Waka Kesiswaan',
    createdAt: STATIC_DATE,
    updatedAt: STATIC_DATE,
  },
];
