import { User } from '../types';

export const TEACHERS: User[] = [
  {
    id: 9999,
    name: 'Admin User',
    code: 'SU',
    email: 'admin@almaarif.id',
    password: 'admin',
    role: 'admin',
  },
  {
    id: 1,
    code: 'A',
    name: "K. Syamsul Ma'arif",
    email: 'syamsul.maarif@almaarif.id',
    password: 'syamsul123',
    role: 'teacher',
  },
  {
    id: 2,
    code: 'B',
    name: 'Ust. Istamar',
    email: 'istamar@almaarif.id',
    password: 'istamar123',
    role: 'teacher',
  },
  {
    id: 3,
    code: 'C',
    name: 'Achmad Qosyidin',
    email: 'achmad.qosyidin@almaarif.id',
    password: 'achmad123',
    role: 'teacher',
  },
  {
    id: 4,
    code: 'D',
    name: 'Nurul Iman Saputra',
    email: 'nurul.iman@almaarif.id',
    password: 'nurul123',
    role: 'teacher',
  },
  {
    id: 5,
    code: 'E',
    name: 'Ilham Aditia Nurohman',
    email: 'ilham.aditia@almaarif.id',
    password: 'ilham123',
    role: 'teacher',
  },
  {
    id: 6,
    code: 'F',
    name: 'Irfan Ramadhan',
    email: 'irfan.ramadhan@almaarif.id',
    password: 'irfan123',
    role: 'teacher',
  },
  {
    id: 7,
    code: 'G',
    name: "Imron Ma'arif",
    email: 'imron.maarif@almaarif.id',
    password: 'imron123',
    role: 'teacher',
  },
  {
    id: 8,
    code: 'H',
    name: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@almaarif.id',
    password: 'ahmad123',
    role: 'teacher',
  },
  {
    id: 9,
    code: 'I',
    name: "Ary Sya'bana",
    email: 'ary.syabana@almaarif.id',
    password: 'ary123',
    role: 'teacher',
  },
  {
    id: 10,
    code: 'J',
    name: 'Ridho Pratama',
    email: 'ridho.pratama@almaarif.id',
    password: 'ridho123',
    role: 'teacher',
  },
  {
    id: 11,
    code: 'K',
    name: 'Asykur',
    email: 'asykur@almaarif.id',
    password: 'asykur123',
    role: 'teacher',
  },
  {
    id: 12,
    code: 'L',
    name: 'Umi Dewi Anjariyah',
    email: 'umi.dewi@almaarif.id',
    password: 'umi123',
    role: 'teacher',
  },
  {
    id: 13,
    code: 'M',
    name: 'Indah Nur Fadhilah',
    email: 'indah.nur@almaarif.id',
    password: 'indah123',
    role: 'teacher',
  },
  {
    id: 14,
    code: 'N',
    name: "Ni'matul Laely",
    email: 'nimatul.laely@almaarif.id',
    password: 'nimatul123',
    role: 'teacher',
  },
  {
    id: 15,
    code: 'O',
    name: 'Tri Lestari',
    email: 'tri.lestari@almaarif.id',
    password: 'tri123',
    role: 'teacher',
  },
  {
    id: 16,
    code: 'P',
    name: 'Istiqomah M.',
    email: 'istiqomah@almaarif.id',
    password: 'istiqomah123',
    role: 'teacher',
  },
  {
    id: 17,
    code: 'Q',
    name: 'Putri Ulfa Sari',
    email: 'putri.ulfa@almaarif.id',
    password: 'putri123',
    role: 'teacher',
  },
  {
    id: 18,
    code: 'R',
    name: 'Nur Hasanah',
    email: 'nur.hasanah@almaarif.id',
    password: 'nur123',
    role: 'teacher',
  },
  {
    id: 19,
    code: 'S',
    name: "Robi'ah Adawiah",
    email: 'robiah.adawiah@almaarif.id',
    password: 'robiah123',
    role: 'teacher',
  },
  {
    id: 20,
    code: 'T',
    name: 'Irfatul Ulum',
    email: 'irfatul.ulum@almaarif.id',
    password: 'irfatul123',
    role: 'teacher',
  },
];
