export const SUBJECTS = [
  {
    id: 1,
    label: 'Iqro',
    value: 'iqro',
    class: '1 Madin',
  },
  {
    id: 2,
    label: 'Fasholatan',
    value: 'fasholatan',
    class: '1 Madin',
  },
  {
    id: 3,
    label: "Imla'",
    value: 'imla',
    class: '1 Madin',
  },
  {
    id: 4,
    label: 'Alala',
    value: 'alala',
    class: '1 Madin',
  },
  {
    id: 5,
    label: 'Dzikir',
    value: 'dzikir',
    class: '1 Madin',
  },
  {
    id: 6,
    label: "Ta'aruf",
    value: 'taaruf',
    class: '2 Madin',
  },
  {
    id: 7,
    label: 'Aqidatul Awam',
    value: 'aqidatul_awam',
    class: '2 Madin',
  },
  {
    id: 8,
    label: 'Izzul Adab',
    value: 'izzul_adab',
    class: '2 Madin',
  },
  {
    id: 9,
    label: 'Mabadi 1-2',
    value: 'mabadi_1_2',
    class: '2 Madin',
  },
  {
    id: 10,
    label: 'Hadayatus Syibyan',
    value: 'hadayatus_syibyan',
    class: '2 Madin',
  },
  {
    id: 11,
    label: 'Hidayatus Syibyan',
    value: 'hidayatus_syibyan',
    class: '2 Madin',
  },
  {
    id: 12,
    label: 'Tuhfatul Athfal',
    value: 'tuhfatul_athfal',
    class: '3 Madin',
  },
  {
    id: 13,
    label: "Tanbihul Muta'allim",
    value: 'tanbihul_mutaalim',
    class: '3 Madin',
  },
  {
    id: 14,
    label: 'Mabadi 3-4',
    value: 'mabadi_3_4',
    class: '3 Madin',
  },
  {
    id: 15,
    label: 'Jurumiyah',
    value: 'jurumiyah',
    class: '3 Madin',
  },
  {
    id: 16,
    label: 'Badiul Amal',
    value: 'badiul_amal',
    class: '3 Madin',
  },
  {
    id: 17,
    label: 'Jauharotut Tauhid',
    value: 'jauharotut_tauhid',
    class: '4 Madin',
  },
  {
    id: 18,
    label: 'Imriti',
    value: 'imriti',
    class: '4 Madin',
  },
  {
    id: 19,
    label: 'Jazariyah',
    value: 'jazariyah',
    class: '4 Madin',
  },
  {
    id: 20,
    label: 'Taisirul Kholaq',
    value: 'taisirul_kholaq',
    class: '4 Madin',
  },
  {
    id: 21,
    label: 'Sulam',
    value: 'sulam',
    class: '4 Madin',
  },
  {
    id: 22,
    label: 'Washoya',
    value: 'washoya',
    class: '5 Madin',
  },
  {
    id: 23,
    label: 'Fathul Qorib',
    value: 'fathul_qorib',
    class: '5 Madin',
  },
  {
    id: 24,
    label: 'Alfiyah',
    value: 'alfiyah',
    class: '5-6 Madin',
  },
  {
    id: 25,
    label: "Risalatul Quro'",
    value: 'risalatul_quro',
    class: '5 Madin',
  },
  {
    id: 26,
    label: 'Kifayatul Awam',
    value: 'kifayatul_awam',
    class: '5 Madin',
  },
  {
    id: 27,
    label: 'Ulumul Barohin',
    value: 'ulumul_barohin',
    class: '6 Madin',
  },
  {
    id: 28,
    label: 'Fathul Manan',
    value: 'fathul_manan',
    class: '6 Madin',
  },
  {
    id: 29,
    label: "Ta'limul Muta'alim",
    value: 'talimul_mutaalim',
    class: '5-6 Madin',
  },
  {
    id: 30,
    label: 'Sulam Taufiq',
    value: 'sulam_taufiq',
    class: '4 Madin',
  },
];
